# Generated by Django 3.1.5 on 2023-06-06 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederItem',
            new_name='OrderItem',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='oreder',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='oreder',
            new_name='order',
        ),
    ]
